
Public Class languages

    Public Function find_lang_words() As langua

        Dim oeh As Integer = 0
        Dim languag As New langua
        Const strings As Int16 = 120
        Array.Resize(languag.chinese, strings)
        Array.Resize(languag.deutsch, strings)
        Array.Resize(languag.english, strings)
        Array.Resize(languag.french, strings)
        Array.Resize(languag.spanish, strings)
        Array.Resize(languag.russian, strings)

        languag.deutsch(oeh) = "&Menü"
        languag.english(oeh) = "&Menu"
        languag.chinese(oeh) = "文件"
        oeh += 1
        languag.deutsch(oeh) = "&Neue Datei STRG+N"
        languag.english(oeh) = "&New File   CTRL+N"
        languag.chinese(oeh) = "新          CTRL+N"
        oeh += 1
        languag.deutsch(oeh) = "&Öffnen        STRG+O"
        languag.english(oeh) = "&Open        CTRL+O"
        languag.chinese(oeh) = "打开        CTRL+O"
        oeh += 1
        languag.deutsch(oeh) = "Speichern   STRG+S"
        languag.english(oeh) = "Save         CTRL+S"
        languag.chinese(oeh) = "保存        CTRL+S"
        oeh += 1
        languag.deutsch(oeh) = "Speichern &unter"
        languag.english(oeh) = "save &as"
        languag.chinese(oeh) = "另存为"
        oeh += 1
        languag.deutsch(oeh) = "Schließen"
        languag.english(oeh) = "&Close"
        languag.chinese(oeh) = "关闭"
        oeh += 1
        languag.deutsch(oeh) = "&Einstellungen"
        languag.english(oeh) = "&Settings"
        languag.chinese(oeh) = "安装"
        oeh += 1
        languag.deutsch(oeh) = "&Beenden    STRG+Q"
        languag.english(oeh) = "&Exit       CTRL+Q"
        languag.chinese(oeh) = "结束        CTRL+Q"
        oeh += 1
        languag.deutsch(oeh) = "&Hilfe"
        languag.english(oeh) = "&Help"
        languag.chinese(oeh) = "帮助"
        oeh += 1
        languag.deutsch(oeh) = "fuer den Programmierer hoffentlich"
        languag.english(oeh) = "for the programmer, I hope so"
        languag.chinese(oeh) = "希望如此"
        oeh += 1
        languag.deutsch(oeh) = "Neue Datei"
        languag.english(oeh) = "new file"
        languag.chinese(oeh) = "开始"
        oeh += 1
        languag.deutsch(oeh) = "Öffnen"
        languag.english(oeh) = "open"
        languag.chinese(oeh) = "打开"
        oeh += 1
        languag.deutsch(oeh) = "Speichern "
        languag.english(oeh) = "save"
        languag.chinese(oeh) = "保存"
        oeh += 1
        languag.deutsch(oeh) = "Schließen"
        languag.english(oeh) = "close"
        languag.chinese(oeh) = "关闭"
        oeh += 1
        languag.deutsch(oeh) = "Drucken"
        languag.english(oeh) = "print"
        languag.chinese(oeh) = "打印"
        oeh += 1
        languag.deutsch(oeh) = "Schrift"
        languag.english(oeh) = "font"
        languag.chinese(oeh) = "字体"
        oeh += 1
        languag.deutsch(oeh) = "Bearbeiten"
        languag.english(oeh) = "change"
        languag.chinese(oeh) = "修改"
        oeh += 1
        languag.deutsch(oeh) = "Neu/Entf."
        languag.english(oeh) = "new/remove"
        languag.chinese(oeh) = "新的/移动"
        oeh += 1
        languag.deutsch(oeh) = "Werkzeug-Streifen"
        languag.english(oeh) = "toolstrips"
        languag.chinese(oeh) = "工具条"
        oeh += 1
        languag.deutsch(oeh) = "Schrift"
        languag.english(oeh) = "font"
        languag.chinese(oeh) = "字体"
        oeh += 1
        languag.deutsch(oeh) = "Neues Element"
        languag.english(oeh) = "new element"
        languag.chinese(oeh) = "新要素"
        oeh += 1
        languag.deutsch(oeh) = "Element löschen"
        languag.english(oeh) = "remove element"
        languag.chinese(oeh) = "移动新要素"
        oeh += 1
        languag.deutsch(oeh) = "Aussschneiden STRG+X"
        languag.english(oeh) = "cut CTRL+X"
        languag.chinese(oeh) = "剪切 CTRL++X"
        oeh += 1
        languag.deutsch(oeh) = "Kopieren STRG+C"
        languag.english(oeh) = "copy CTRL+C"
        languag.chinese(oeh) = "复制 CTRL+C"
        oeh += 1
        languag.deutsch(oeh) = "Einfügen STRG+V"
        languag.english(oeh) = "paste CTRL+V"
        languag.chinese(oeh) = "粘贴 CTRL+V"
        oeh += 1
        languag.deutsch(oeh) = "Einstellungen"
        languag.english(oeh) = "settings"
        languag.chinese(oeh) = "安装"
        oeh += 1
        languag.deutsch(oeh) = "In Deskbar zeigen"
        languag.english(oeh) = "show in Deskbar"
        languag.chinese(oeh) = "桌面"
        oeh += 1
        languag.deutsch(oeh) = "Sprache"
        languag.english(oeh) = "language"
        languag.chinese(oeh) = "语言"
        oeh += 1
        languag.deutsch(oeh) = "ok"
        languag.english(oeh) = "ok"
        languag.chinese(oeh) = "ok"
        oeh += 1
        languag.deutsch(oeh) = "Kopieren"
        languag.english(oeh) = "copy"
        languag.chinese(oeh) = "复制"
        oeh += 1
        languag.deutsch(oeh) = "Ausschneiden"
        languag.english(oeh) = "cut"
        languag.chinese(oeh) = "剪切"
        oeh += 1
        languag.deutsch(oeh) = "Einfuegen"
        languag.english(oeh) = "paste"
        languag.chinese(oeh) = "粘贴"
        oeh += 1
        languag.deutsch(oeh) = "Löschen"
        languag.english(oeh) = "delete"
        languag.chinese(oeh) = "删除"
        oeh += 1
        languag.deutsch(oeh) = "Suchen"
        languag.english(oeh) = "search"
        languag.chinese(oeh) = "搜索"
        oeh += 1
        languag.deutsch(oeh) = "Neu darunter [einfg]"
        languag.english(oeh) = "new under [ins]"
        languag.chinese(oeh) = "新的"
        oeh += 1
        languag.deutsch(oeh) = "Umbenennen "
        languag.english(oeh) = "rename"
        languag.chinese(oeh) = "重命名"
        oeh += 1
        languag.deutsch(oeh) = "Löschen [entf]"
        languag.english(oeh) = "remove [del]"
        languag.chinese(oeh) = "移动"
        oeh += 1
        languag.deutsch(oeh) = "Speichern"
        languag.english(oeh) = "save"
        languag.chinese(oeh) = "保存"
        oeh += 1
        languag.deutsch(oeh) = "Desktop-Notiz"
        languag.english(oeh) = "desk note"
        languag.chinese(oeh) = "新窗口"
        oeh += 1
        languag.deutsch(oeh) = "Möchten Sie den Knoten wirklich löschen?"
        languag.english(oeh) = "Do you want to remove this node?"
        languag.chinese(oeh) = "是否移动此节点？"
        oeh += 1
        languag.deutsch(oeh) = "Ja"
        languag.english(oeh) = "Yes"
        languag.chinese(oeh) = "是"
        oeh += 1
        languag.deutsch(oeh) = "Nein"
        languag.english(oeh) = "No"
        languag.chinese(oeh) = "否"
        oeh += 1
        languag.deutsch(oeh) = "Baum in dem die Notizen geordnet sind"
        languag.english(oeh) = "notes tree"
        languag.chinese(oeh) = "词条正确"
        oeh += 1
        languag.deutsch(oeh) = "Anzeige der jeweiligen Notiz"
        languag.english(oeh) = "place where Notes are shown"
        languag.chinese(oeh) = "显示节点所在位置"
        oeh += 1
        languag.deutsch(oeh) = "Zeigen/Ausblenden"
        languag.english(oeh) = "Show/Hide"
        languag.chinese(oeh) = "显示/隐藏"
        oeh += 1
        languag.deutsch(oeh) = "Suche"
        languag.english(oeh) = "search"
        languag.chinese(oeh) = "搜索"
        oeh += 1
        languag.deutsch(oeh) = "Suchen"
        languag.english(oeh) = "search"
        languag.chinese(oeh) = "搜索"
        oeh += 1
        languag.deutsch(oeh) = "Fertig"
        languag.english(oeh) = "back"
        languag.chinese(oeh) = "完成"
        oeh += 1
        languag.deutsch(oeh) = "Alle Knoten durchsuchen?"
        languag.english(oeh) = "search all nodes?"
        languag.chinese(oeh) = "搜索所有词条？"
        oeh += 1
        languag.deutsch(oeh) = "Ergebnisse:"
        languag.english(oeh) = "results:"
        languag.chinese(oeh) = "结果"
        oeh += 1
        languag.deutsch(oeh) = "Wollen Sie vorher speichern?"
        languag.english(oeh) = "Do you want to save before?"
        languag.chinese(oeh) = "是否将前面保存？"
        oeh += 1
        languag.deutsch(oeh) = "von vorn beginnen"
        languag.english(oeh) = "begin again"
        languag.chinese(oeh) = "重新开始"
        oeh += 1
        languag.deutsch(oeh) = "von vorn beginnen"
        languag.english(oeh) = "begin again"
        languag.chinese(oeh) = "重新开始"
        oeh += 1
        languag.deutsch(oeh) = "Vorhandene Daten werden gelöscht."
        languag.english(oeh) = "Data will be lost."
        languag.chinese(oeh) = "消除日期"
        oeh += 1
        languag.deutsch(oeh) = "Sind sie sicher, dass Sie vorn beginnen wollen?"
        languag.english(oeh) = "Are you sure to begin again?"
        languag.chinese(oeh) = "是否决定重新开始?"
        oeh += 1
        languag.deutsch(oeh) = "Möchten Sie vorher speichern?"
        languag.english(oeh) = "Do you want to save before?"
        languag.chinese(oeh) = "是否将前面保存？"
        oeh += 1
        languag.deutsch(oeh) = "OK"
        languag.english(oeh) = "OK"
        languag.chinese(oeh) = "OK"
        oeh += 1
        languag.deutsch(oeh) = "abbrechen"
        languag.english(oeh) = "cancel"
        languag.chinese(oeh) = "中止"
        oeh += 1
        languag.deutsch(oeh) = "Kopieren"
        languag.english(oeh) = "copy"
        languag.chinese(oeh) = "复制"
        oeh += 1
        languag.deutsch(oeh) = "Ausschneiden"
        languag.english(oeh) = "cut"
        languag.chinese(oeh) = "剪切"
        oeh += 1
        languag.deutsch(oeh) = "Einfügen"
        languag.english(oeh) = "paste"
        languag.chinese(oeh) = "粘贴"
        oeh += 1
        languag.deutsch(oeh) = "normale Schrift"
        languag.english(oeh) = "regular font"
        languag.chinese(oeh) = "常规字体"
        oeh += 1
        languag.deutsch(oeh) = "Fett-Schrift"
        languag.english(oeh) = "bold font"
        languag.chinese(oeh) = "黑体"
        oeh += 1
        languag.deutsch(oeh) = "Kursiv-Schrift"
        languag.english(oeh) = "italic font"
        languag.chinese(oeh) = "斜体"

        oeh += 1
        languag.deutsch(oeh) = "unterstrichen"
        languag.english(oeh) = "underline"
        languag.chinese(oeh) = "强调"
        oeh += 1
        languag.deutsch(oeh) = "durchgestrichen"
        languag.english(oeh) = "strikeout"
        languag.chinese(oeh) = "划去"
        oeh += 1
        languag.deutsch(oeh) = "grössere Schrift"
        languag.english(oeh) = "bigger font"
        languag.chinese(oeh) = "大字体"
        oeh += 1
        languag.deutsch(oeh) = "kleinere Schrift"
        languag.english(oeh) = "smaller font"
        languag.chinese(oeh) = "小字体"
        oeh += 1
        languag.deutsch(oeh) = "Zusammenfassen"
        languag.english(oeh) = "together in one node"
        languag.chinese(oeh) = "一起，在一个节点"
        oeh += 1
        languag.deutsch(oeh) = "Info + Hilfe + Feedback"
        languag.english(oeh) = "info + help + feedback"
        languag.chinese(oeh) = "信息+帮助+反馈"
        oeh += 1
        languag.deutsch(oeh) = "alles"
        languag.english(oeh) = "everything"
        languag.chinese(oeh) = "一切"
        oeh += 1
        languag.deutsch(oeh) = "unterhalb des markierten Knotens"
        languag.english(oeh) = "inside the marked node"
        languag.chinese(oeh) = "内的标记节点"
        oeh += 1
        languag.deutsch(oeh) = "Keine Datei wurde geladen."
        languag.english(oeh) = "No file is loaded."
        languag.chinese(oeh) = "没有文件被加载。"
        oeh += 1
        languag.deutsch(oeh) = "Fehler beim Laden von XML Code:"
        languag.english(oeh) = "Error when loading xml code:"
        languag.chinese(oeh) = "错误时加载XML代码:"
        oeh += 1
        languag.deutsch(oeh) = "Passwort setzen"
        languag.english(oeh) = "set password"
        languag.chinese(oeh) = "设置密码"
        oeh += 1
        languag.deutsch(oeh) = "altes Passwort"
        languag.english(oeh) = "old password"
        languag.chinese(oeh) = "旧密码"
        oeh += 1
        languag.deutsch(oeh) = "neues Passwort"
        languag.english(oeh) = "new password"
        languag.chinese(oeh) = "新密码"
        oeh += 1
        languag.deutsch(oeh) = "wiederholen"
        languag.english(oeh) = "again"
        languag.chinese(oeh) = "再次"
        oeh += 1
        languag.deutsch(oeh) = "Das Passwort darf nicht mehr als 24 Zeichen haben."
        languag.english(oeh) = "Not more than 24 characters are allowed."
        languag.chinese(oeh) = "不超过24个字符是允许的。"
        oeh += 1
        languag.deutsch(oeh) = "Das alte Passwort ist falsch."
        languag.english(oeh) = "The old password is wrong."
        languag.chinese(oeh) = "旧密码是错误的。"
        oeh += 1
        languag.deutsch(oeh) = "Passwort"
        languag.english(oeh) = "password"
        languag.chinese(oeh) = "密码"
        oeh += 1
        languag.deutsch(oeh) = "Passwort falsch oder Datei fehlerhaft"
        languag.english(oeh) = "wrong password or incorrect file"
        languag.chinese(oeh) = "错误的密码或不正确的文件"
        oeh += 1
        languag.deutsch(oeh) = "Die letzten beiden Eingaben sind nicht gleich."
        languag.english(oeh) = "The last 3 entrys are not equal."
        languag.chinese(oeh) = "最后的3项不相等。"
        oeh += 1
        languag.deutsch(oeh) = "Leeres Feld bedeutet kein Passwort."
        languag.english(oeh) = "Empty textbox means no password."
        languag.chinese(oeh) = "空文本就没有密码。"
        oeh += 1
        languag.deutsch(oeh) = "Bild einfügen"
        languag.english(oeh) = "insert picture"
        languag.chinese(oeh) = "插入图片"
        oeh += 1
        languag.deutsch(oeh) = "Datum einfügen"
        languag.english(oeh) = "insert date"
        languag.chinese(oeh) = "插入日期"
        oeh += 1
        languag.deutsch(oeh) = "Hintergrundfarbe"
        languag.english(oeh) = "background color"
        languag.chinese(oeh) = "背景颜色"
        oeh += 1
        languag.deutsch(oeh) = "Minimieren"
        languag.english(oeh) = "minimize"
        languag.chinese(oeh) = "最小化"
        oeh += 1
        languag.deutsch(oeh) = "Schließen"
        languag.english(oeh) = "close"
        languag.chinese(oeh) = "关闭"
        oeh += 1
        languag.deutsch(oeh) = "Desktop-Notitz-Fensterrand einblenden"
        languag.english(oeh) = "show desknote borders"
        languag.chinese(oeh) = "显示办公桌边界"
        oeh += 1
        languag.deutsch(oeh) = "Hintergrundfarbe"
        languag.english(oeh) = "Background Color"
        languag.chinese(oeh) = "背景颜色"
        oeh += 1
        languag.deutsch(oeh) = "Schriftfarbe"
        languag.english(oeh) = "Font Color"
        languag.chinese(oeh) = "字体颜色"
        oeh += 1
        languag.deutsch(oeh) = "Sicherungen"
        languag.english(oeh) = "backup copies"
        languag.chinese(oeh) = "备份"
        oeh += 1
        languag.deutsch(oeh) = "Autostart"
        languag.english(oeh) = "autorun"
        languag.chinese(oeh) = "自动运行"
        oeh += 1
        languag.deutsch(oeh) = "Farbe"
        languag.english(oeh) = "color"
        languag.chinese(oeh) = "颜色"
        oeh += 1
        languag.deutsch(oeh) = "Passwort"
        languag.english(oeh) = "password"
        languag.chinese(oeh) = "密码"
        oeh += 1
        languag.deutsch(oeh) = "Pfad+Datei"
        languag.english(oeh) = "Path+File"
        languag.chinese(oeh) = "路径+文件"
        oeh += 1
        languag.deutsch(oeh) = "Die Datei muss auf .alx enden!"
        languag.english(oeh) = "File has to end with .alx !"
        languag.chinese(oeh) = "文件已经结束了。"
        oeh += 1
        languag.deutsch(oeh) = "Export"
        languag.english(oeh) = "export"
        languag.chinese(oeh) = "出口"
        oeh += 1
        languag.deutsch(oeh) = "in rtf"
        languag.english(oeh) = "in rtf"
        languag.chinese(oeh) = "以RTF"
        oeh += 1
        languag.deutsch(oeh) = "in ansi txt"
        languag.english(oeh) = "in ansi txt"
        languag.chinese(oeh) = "在ANSI txt 的"
        oeh += 1
        languag.deutsch(oeh) = "in unicode txt"
        languag.english(oeh) = "in unicode txt"
        languag.chinese(oeh) = "在Unicode txt的"
        oeh += 1
        languag.deutsch(oeh) = "daneben [Enter]"
        languag.english(oeh) = "next [Enter]"
        languag.chinese(oeh) = "下一页[进入"
        oeh += 1
        languag.deutsch(oeh) = "darunter [einfg]"
        languag.english(oeh) = "under [insert]"
        languag.chinese(oeh) = "在[插入]"
        oeh += 1
        languag.deutsch(oeh) = "Neu daneben [Enter]"
        languag.english(oeh) = "new next [Enter]"
        languag.chinese(oeh) = "新的未来[进入] "
        oeh += 1
        languag.deutsch(oeh) = "ganze Wörter"
        languag.english(oeh) = "whole words"
        languag.chinese(oeh) = "全字"
        oeh += 1
        languag.deutsch(oeh) = "Groß-/Klein-Schreibung beachten"
        languag.english(oeh) = "case sensitive"
        languag.chinese(oeh) = "区分大小写"
        oeh += 1
        languag.deutsch(oeh) = ChrW(8226) + " Eine Desktop-Notitz erstellt man mit dem Menü eines Knotens und erreicht man dann über das Menü des Trayicons." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
     ChrW(8226) + " Einzelne Knoten lassen sich als rtf Datei zusammenfassen, die z.B. mit Wordpad lesbar sind." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
     ChrW(8226) + " Erstellt man eine Verknüpfung mit dem Ziel ""C:\Ort1\notizen.exe"" -min ""C:\Dokumente und Einstellungen\Benutzer\Eigene Dateien\Notizen\datei.alx"" also erst notizen.exe und die alx-Datei, dann öffnet sich das Programm zusammen mit der Notizendatei. Beide Ortsangaben müssen am Besten in Anführungszeichen stehen. Stellt man diese Verknüpfung in den Autostartordner, so hat man immer seine gut sortierten Notizen zur Hand." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
     ChrW(8226) + " Die Anhabe /min sorgt als Programmstartangabe z.B. in einer Verknüpfung für ein minimiertes Hauptfenster bei Beginn. (notizen.exe /min Zieldatei)"" " + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
     ChrW(8226) + " Startet man Notizen .Net mit Adminrechten kann danach eine alx-Datei durch den Explorerer erkannt werden."

        languag.english(oeh) = ChrW(8226) + " A desknote can be created by using the menu of the node and can be reached by the trayicon menu." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " Nodes can be summed up as rtf file, witch can be read with Wordpad, Word or OpenOffice." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " Create a Link with with a destination: ""C:\Ort1\notizen.exe"" -min ""C:\Dokumente und Einstellungen\Benutzer\Eigene Dateien\Notizen\datei.alx"" , first notizen.exe and the alx file, the program will be opend by opening the File. Both Locations should be better into double quotes. If you put the link into the autostart folder you have your notes by starting the Computer." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " The argument /min after notizen.exe, maybe in a line of a link, makes the programm running minimized at startup. (notizen.exe /min destination file)"" " + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
     ChrW(8226) + "If you run Notizen .Net with Administrator permissions once, the explorer will know Notizen .NET alx Files."
        languag.chinese(oeh) = ChrW(8226) + " A desknote can be created by using the menu of the node and can be reached by the trayicon menu." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " Nodes can be summed up as rtf file, witch can be read with Wordpad, Word or OpenOffice." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " Create a Link with with a destination: ""C:\Ort1\notizen.exe"" -min ""C:\Dokumente und Einstellungen\Benutzer\Eigene Dateien\Notizen\datei.alx"" , first notizen.exe and the alx file, the program will be opend by opening the File. Both Locations should be better into double quotes. If you put the link into the autostart folder you have your notes by starting the Computer." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " The argument /min after notizen.exe, maybe in a line of a link, makes the programm running minimized at startup. (notizen.exe /min destination file)"" " + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
     ChrW(8226) + "If you run Notizen .Net with Administrator permissions once, the explorer will know Notizen .NET alx Files."

        oeh += 1
        languag.deutsch(oeh) = "persönliche Meinung / Fehlermeldung / Feature-Vorschlag"
        languag.english(oeh) = "opinion / bug report / feature request"
        languag.chinese(oeh) = "意见/错误报告/功能要求"
        oeh += 1
        languag.deutsch(oeh) = "schließen"
        languag.english(oeh) = "close"
        languag.chinese(oeh) = "关闭"
        oeh += 1
        languag.deutsch(oeh) = "senden"
        languag.english(oeh) = "send"
        languag.chinese(oeh) = "发送"
        oeh += 1
        languag.deutsch(oeh) = "Nach 3 Feebacks kann man erst wieder am nächsten Tag senden."
        languag.english(oeh) = "After 3 Feedbacks sending feedback is only possible tomorrow."
        languag.chinese(oeh) = "3反馈后，发送反馈是唯一可能的明天。"
        oeh += 1
        languag.deutsch(oeh) = "Geben sie mindestens 10 Zeichen ein!"
        languag.english(oeh) = "A minimal input of 10 characters is requiered."
        languag.chinese(oeh) = "10个字符最小输入需求列表。"
        oeh += 1
        languag.deutsch(oeh) = "Feedback konnte nicht gesendet werden."
        languag.english(oeh) = "Feedback was not transmitted."
        languag.chinese(oeh) = "反馈不传染。"
        oeh += 1
        languag.deutsch(oeh) = "minimierter autostart"
        languag.english(oeh) = "minimized autorun"
        languag.chinese(oeh) = "最小化自动运行"
        oeh += 1
        languag.deutsch(oeh) = "automatisches speichern jede"
        languag.english(oeh) = "automatic saves every"
        languag.chinese(oeh) = "自动保存每个"
        oeh += 1
        languag.deutsch(oeh) = "Sekunde"
        languag.english(oeh) = "seconds"
        languag.chinese(oeh) = "秒"
        oeh += 1
        languag.deutsch(oeh) = "scroll"
        languag.english(oeh) = "scroll"
        languag.chinese(oeh) = "滚动"








        oeh = 0
        languag.french(oeh) = "Menu"
        oeh += 1
        languag.french(oeh) = "Nouveau fichier Ctrl + N"
        oeh += 1
        languag.french(oeh) = "Ouvrir Ctrl + O"
        oeh += 1
        languag.french(oeh) = "Enregistrer CTRL + S"
        oeh += 1
        languag.french(oeh) = "Enregistrer sous"
        oeh += 1
        languag.french(oeh) = "Fermer"
        oeh += 1
        languag.french(oeh) = "Paramètres"
        oeh += 1
        languag.french(oeh) = "Quitter Ctrl + Q"
        oeh += 1
        languag.french(oeh) = "Aide"
        oeh += 1
        languag.french(oeh) = "pour le programmeur, je l'espère» "
        oeh += 1
        languag.french(oeh) = "nouveau fichier"
        oeh += 1
        languag.french(oeh) = "ouvert"
        oeh += 1
        languag.french(oeh) = "sauver"
        oeh += 1
        languag.french(oeh) = "close"
        oeh += 1
        languag.french(oeh) = "print"
        oeh += 1
        languag.french(oeh) = "font"
        oeh += 1
        languag.french(oeh) = "changement"
        oeh += 1
        languag.french(oeh) = "new / Supprimer"
        oeh += 1
        languag.french(oeh) = "toolstrips"
        oeh += 1
        languag.french(oeh) = "font"
        oeh += 1
        languag.french(oeh) = "nouvel élément"
        oeh += 1
        languag.french(oeh) = "Retirer l'élément"
        oeh += 1
        languag.french(oeh) = "Couper Ctrl + X"
        oeh += 1
        languag.french(oeh) = "Copier Ctrl + C"
        oeh += 1
        languag.french(oeh) = "Coller Ctrl + V"
        oeh += 1
        languag.french(oeh) = "Paramètres"
        oeh += 1
        languag.french(oeh) = "Afficher dans la barre de Bureau"
        oeh += 1
        languag.french(oeh) = "language"
        oeh += 1
        languag.french(oeh) = "ok"
        oeh += 1
        languag.french(oeh) = "Copier"
        oeh += 1
        languag.french(oeh) = "Couper"
        oeh += 1
        languag.french(oeh) = "coller"
        oeh += 1
        languag.french(oeh) = "supprimer"
        oeh += 1
        languag.french(oeh) = "Recherche"
        oeh += 1
        languag.french(oeh) = "Recherche"
        oeh += 1
        languag.french(oeh) = "Nouveau sous [Ins]"
        oeh += 1
        languag.french(oeh) = "Renommer"
        oeh += 1
        languag.french(oeh) = "supprimer [Suppr]"
        oeh += 1
        languag.french(oeh) = "save"
        oeh += 1
        languag.french(oeh) = "note desk"
        oeh += 1
        languag.french(oeh) = "Voulez-vous supprimer ce noeud?"
        oeh += 1
        languag.french(oeh) = "Oui"
        oeh += 1
        languag.french(oeh) = "Non"
        oeh += 1
        languag.french(oeh) = "Notes arbre"
        oeh += 1
        languag.french(oeh) = "lieu où les notes sont affichées"
        oeh += 1
        languag.french(oeh) = "Afficher / Masquer"
        oeh += 1
        languag.french(oeh) = "Recherche"
        oeh += 1
        languag.french(oeh) = "Retour"
        oeh += 1
        languag.french(oeh) = "rechercher tous les nœuds? "
        oeh += 1
        languag.french(oeh) = "Results:"
        oeh += 1
        languag.french(oeh) = "Voulez-vous enregistrer avant?"
        oeh += 1
        languag.french(oeh) = "recommencer"
        oeh += 1
        languag.french(oeh) = "recommencer"
        oeh += 1
        languag.french(oeh) = "Les données seront perdues."
        oeh += 1
        languag.french(oeh) = "Etes-vous sûr de vouloir recommencer?"
        oeh += 1
        languag.french(oeh) = "Voulez-vous enregistrer avant?"
        oeh += 1
        languag.french(oeh) = "OK"
        oeh += 1
        languag.french(oeh) = "Annuler"
        oeh += 1
        languag.french(oeh) = "Copier"
        oeh += 1
        languag.french(oeh) = "Couper"
        oeh += 1
        languag.french(oeh) = "coller"
        oeh += 1
        languag.french(oeh) = "font régulièrement"
        oeh += 1
        languag.french(oeh) = "font bold"
        oeh += 1
        languag.french(oeh) = "italique"
        oeh += 1
        languag.french(oeh) = "underline"
        oeh += 1
        languag.french(oeh) = "barrées"
        oeh += 1
        languag.french(oeh) = "font plus grands"
        oeh += 1
        languag.french(oeh) = "petits caractères"
        oeh += 1
        languag.french(oeh) = "ensemble dans un noeud"
        oeh += 1
        languag.french(oeh) = "info + aide + feedback» "
        oeh += 1
        languag.french(oeh) = "tout"
        oeh += 1
        languag.french(oeh) = "à l'intérieur du nœud marqué"
        oeh += 1
        languag.french(oeh) = "Aucun fichier n'est chargé."
        oeh += 1
        languag.french(oeh) = "Erreur lors du chargement de code XML:"
        oeh += 1
        languag.french(oeh) = "Mot de code"
        oeh += 1
        languag.french(oeh) = "ancien mot de passe"
        oeh += 1
        languag.french(oeh) = "nouveau mot de passe"
        oeh += 1
        languag.french(oeh) = "à nouveau"
        oeh += 1
        languag.french(oeh) = "caractères Pas plus de 24 ans sont autorisées."
        oeh += 1
        languag.french(oeh) = "L'ancien mot de passe est erroné."
        oeh += 1
        languag.french(oeh) = "password"
        oeh += 1
        languag.french(oeh) = "mauvais mot de passe ou un fichier incorrect"
        oeh += 1
        languag.french(oeh) = "Les 3 dernières Entrys ne sont pas égaux."
        oeh += 1
        languag.french(oeh) = "zone de texte vide signifie qu'aucun mot de passe."
        oeh += 1
        languag.french(oeh) = "Insérer image"
        oeh += 1
        languag.french(oeh) = "insérer la date"
        oeh += 1
        languag.french(oeh) = "couleur de fond"
        oeh += 1
        languag.french(oeh) = "Minimize"
        oeh += 1
        languag.french(oeh) = "close"
        oeh += 1
        languag.french(oeh) = "Afficher les frontières desknote"
        oeh += 1
        languag.french(oeh) = "Couleur de fond"
        oeh += 1
        languag.french(oeh) = "Font Color"
        oeh += 1
        languag.french(oeh) = "copies de sauvegarde"
        oeh += 1
        languag.french(oeh) = "autorun"
        oeh += 1
        languag.french(oeh) = "color"
        oeh += 1
        languag.french(oeh) = "password"
        oeh += 1
        languag.french(oeh) = "Path + File"
        oeh += 1
        languag.french(oeh) = "Le fichier a pour terminer. alx! "
        oeh += 1
        languag.french(oeh) = "export"
        oeh += 1
        languag.french(oeh) = "dans le rtf"
        oeh += 1
        languag.french(oeh) = "dans la norme ANSI txt"
        oeh += 1
        languag.french(oeh) = "IN TXT unicode"
        oeh += 1
        languag.french(oeh) = "next [Entrée]"
        oeh += 1
        languag.french(oeh) = "en vertu de [insérer]"
        oeh += 1
        languag.french(oeh) = "prochain nouveau sur [Entrée]"
        oeh += 1
        languag.french(oeh) = "Mot entier"
        oeh += 1
        languag.french(oeh) = "case sensitive"
        oeh += 1
        languag.french(oeh) = ChrW(8226) + " A desknote can be created by using the menu of the node and can be reached by the trayicon menu." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " Nodes can be summed up as rtf file, witch can be read with Wordpad, Word or OpenOffice." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " Create a Link with with a destination: ""C:\Ort1\notizen.exe"" -min ""C:\Dokumente und Einstellungen\Benutzer\Eigene Dateien\Notizen\datei.alx"" , first notizen.exe and the alx file, the program will be opend by opening the File. Both Locations should be better into double quotes. If you put the link into the autostart folder you have your notes by starting the Computer." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " The argument /min after notizen.exe, maybe in a line of a link, makes the programm running minimized at startup. (notizen.exe /min destination file)"" " + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
     ChrW(8226) + "If you run Notizen .Net with Administrator permissions once, the explorer will know Notizen .NET alx Files."
        oeh += 1
        languag.french(oeh) = "opinion / rapport de bug / demande de fonctionnalité"
        oeh += 1
        languag.french(oeh) = "close"
        oeh += 1
        languag.french(oeh) = "Envoyer"
        oeh += 1
        languag.french(oeh) = "Après 3 Feedbacks rétroaction d'envoi est seulement possible demain."
        oeh += 1
        languag.french(oeh) = "Un apport minimal de 10 caractères est requiered. "
        oeh += 1
        languag.french(oeh) = "évaluation n'a pas été transmise"
        oeh += 1
        languag.french(oeh) = "minimisées démarrage automatique"
        oeh += 1
        languag.french(oeh) = "Sauvegarde automatique"
        oeh += 1
        languag.french(oeh) = "Seconds"
        oeh += 1
        languag.french(oeh) = "défilement"



        'MsgBox(oeh)
        oeh = 0
        languag.spanish(oeh) = "Menú"
        oeh += 1
        languag.spanish(oeh) = "Nuevo archivo Ctrl + N"
        oeh += 1
        languag.spanish(oeh) = "Abrir Ctrl + O"
        oeh += 1
        languag.spanish(oeh) = "Guardar Ctrl + S"
        oeh += 1
        languag.spanish(oeh) = "guardar como"
        oeh += 1
        languag.spanish(oeh) = "Cerrar"
        oeh += 1
        languag.spanish(oeh) = "Configuración"
        oeh += 1
        languag.spanish(oeh) = "Salir Ctrl + Q"
        oeh += 1
        languag.spanish(oeh) = "Ayuda"
        oeh += 1
        languag.spanish(oeh) = "para el programador, así lo espero"
        oeh += 1
        languag.spanish(oeh) = "archivo"
        oeh += 1
        languag.spanish(oeh) = "abierta"
        oeh += 1
        languag.spanish(oeh) = "guardar"
        oeh += 1
        languag.spanish(oeh) = "cerca"
        oeh += 1
        languag.spanish(oeh) = "print"
        oeh += 1
        languag.spanish(oeh) = "font"
        oeh += 1
        languag.spanish(oeh) = "cambio"
        oeh += 1
        languag.spanish(oeh) = "nuevo / eliminar"
        oeh += 1
        languag.spanish(oeh) = "toolstrips"
        oeh += 1
        languag.spanish(oeh) = "font"
        oeh += 1
        languag.spanish(oeh) = "nuevo elemento"
        oeh += 1
        languag.spanish(oeh) = "eliminar elemento"
        oeh += 1
        languag.spanish(oeh) = "Cortar Ctrl + X"
        oeh += 1
        languag.spanish(oeh) = "Copiar Ctrl + C"
        oeh += 1
        languag.spanish(oeh) = "Pegar Ctrl + V"
        oeh += 1
        languag.spanish(oeh) = "Configuración"
        oeh += 1
        languag.spanish(oeh) = "Mostrar en la barra del escritorio"
        oeh += 1
        languag.spanish(oeh) = "idioma"
        oeh += 1
        languag.spanish(oeh) = "ok"
        oeh += 1
        languag.spanish(oeh) = "copia"
        oeh += 1
        languag.spanish(oeh) = "corte"
        oeh += 1
        languag.spanish(oeh) = "Pegar"
        oeh += 1
        languag.spanish(oeh) = "borrar"
        oeh += 1
        languag.spanish(oeh) = "Buscar"
        oeh += 1
        languag.spanish(oeh) = "Buscar"
        oeh += 1
        languag.spanish(oeh) = "nuevo bajo [INS]"
        oeh += 1
        languag.spanish(oeh) = "Renombrar"
        oeh += 1
        languag.spanish(oeh) = "eliminar [del]"
        oeh += 1
        languag.spanish(oeh) = "guardar"
        oeh += 1
        languag.spanish(oeh) = "nota de escritorio"
        oeh += 1
        languag.spanish(oeh) = "¿Desea eliminar este nodo?"
        oeh += 1
        languag.spanish(oeh) = "Sí"
        oeh += 1
        languag.spanish(oeh) = "No"
        oeh += 1
        languag.spanish(oeh) = "toma nota de árbol"
        oeh += 1
        languag.spanish(oeh) = "lugar donde se muestran Notas"
        oeh += 1
        languag.spanish(oeh) = "Mostrar / Ocultar"
        oeh += 1
        languag.spanish(oeh) = "Buscar"
        oeh += 1
        languag.spanish(oeh) = "Volver"
        oeh += 1
        languag.spanish(oeh) = "buscar todos los nodos?"
        oeh += 1
        languag.spanish(oeh) = "resultados"
        oeh += 1
        languag.spanish(oeh) = "¿Desea guardar antes?"
        oeh += 1
        languag.spanish(oeh) = "empezar de nuevo"
        oeh += 1
        languag.spanish(oeh) = "empezar de nuevo"
        oeh += 1
        languag.spanish(oeh) = "Los datos se perderán."
        oeh += 1
        languag.spanish(oeh) = "¿Estás seguro de volver a empezar?"
        oeh += 1
        languag.spanish(oeh) = "¿Desea guardar antes?"
        oeh += 1
        languag.spanish(oeh) = "OK"
        oeh += 1
        languag.spanish(oeh) = "cancelar"
        oeh += 1
        languag.spanish(oeh) = "copia"
        oeh += 1
        languag.spanish(oeh) = "corte"
        oeh += 1
        languag.spanish(oeh) = "Pegar"
        oeh += 1
        languag.spanish(oeh) = "fuente regular"
        oeh += 1
        languag.spanish(oeh) = "negrita"
        oeh += 1
        languag.spanish(oeh) = "cursiva"
        oeh += 1
        languag.spanish(oeh) = "subrayado"
        oeh += 1
        languag.spanish(oeh) = "tachado"
        oeh += 1
        languag.spanish(oeh) = "fuente mayor"
        oeh += 1
        languag.spanish(oeh) = "fuente más pequeña"
        oeh += 1
        languag.spanish(oeh) = "juntos en un nodo"
        oeh += 1
        languag.spanish(oeh) = "info + ayuda + de votos"
        oeh += 1
        languag.spanish(oeh) = "todo"
        oeh += 1
        languag.spanish(oeh) = "dentro del nodo marcado"
        oeh += 1
        languag.spanish(oeh) = "No existe el fichero está cargado."
        oeh += 1
        languag.spanish(oeh) = "Error al cargar el código XML:"
        oeh += 1
        languag.spanish(oeh) = "Set Password"
        oeh += 1
        languag.spanish(oeh) = "contraseña antigua"
        oeh += 1
        languag.spanish(oeh) = "nueva contraseña"
        oeh += 1
        languag.spanish(oeh) = "nuevo"
        oeh += 1
        languag.spanish(oeh) = "(personajes No más de 24 están permitidas.)"
        oeh += 1
        languag.spanish(oeh) = "La contraseña antigua es incorrecta."
        oeh += 1
        languag.spanish(oeh) = "contraseña"
        oeh += 1
        languag.spanish(oeh) = "contraseña equivocada o incorrecta de archivo"
        oeh += 1
        languag.spanish(oeh) = "Los 3 últimos Juegos PSP no son iguales."
        oeh += 1
        languag.spanish(oeh) = "texto vacío significa que no hay contraseña."
        oeh += 1
        languag.spanish(oeh) = "Insertar imagen"
        oeh += 1
        languag.spanish(oeh) = "insertar fecha"
        oeh += 1
        languag.spanish(oeh) = "color de fondo"
        oeh += 1
        languag.spanish(oeh) = "minimizar"
        oeh += 1
        languag.spanish(oeh) = "cerca"
        oeh += 1
        languag.spanish(oeh) = "Mostrar las fronteras Desknote"
        oeh += 1
        languag.spanish(oeh) = "Color de fondo"
        oeh += 1
        languag.spanish(oeh) = "Color de fuente"
        oeh += 1
        languag.spanish(oeh) = "copias de seguridad"
        oeh += 1
        languag.spanish(oeh) = "autorun"
        oeh += 1
        languag.spanish(oeh) = "color"
        oeh += 1
        languag.spanish(oeh) = "contraseña"
        oeh += 1
        languag.spanish(oeh) = "Ruta + Archivo"
        oeh += 1
        languag.spanish(oeh) = "El archivo tiene que terminar con .alx"
        oeh += 1
        languag.spanish(oeh) = "exportación"
        oeh += 1
        languag.spanish(oeh) = "en rtf"
        oeh += 1
        languag.spanish(oeh) = "en ANSI txt"
        oeh += 1
        languag.spanish(oeh) = "en TXT Unicode"
        oeh += 1
        languag.spanish(oeh) = "Siguiente [Enter]"
        oeh += 1
        languag.spanish(oeh) = "en [insertar]"
        oeh += 1
        languag.spanish(oeh) = "nuevo siguiente [Enter]"
        oeh += 1
        languag.spanish(oeh) = "palabras completas"
        oeh += 1
        languag.spanish(oeh) = "asunto sensible"
        oeh += 1
        languag.spanish(oeh) = ChrW(8226) + " A desknote can be created by using the menu of the node and can be reached by the trayicon menu." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " Nodes can be summed up as rtf file, witch can be read with Wordpad, Word or OpenOffice." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " Create a Link with with a destination: ""C:\Ort1\notizen.exe"" -min ""C:\Dokumente und Einstellungen\Benutzer\Eigene Dateien\Notizen\datei.alx"" , first notizen.exe and the alx file, the program will be opend by opening the File. Both Locations should be better into double quotes. If you put the link into the autostart folder you have your notes by starting the Computer." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " The argument /min after notizen.exe, maybe in a line of a link, makes the programm running minimized at startup. (notizen.exe /min destination file)"" " + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
     ChrW(8226) + "If you run Notizen .Net with Administrator permissions once, the explorer will know Notizen .NET alx Files."
        oeh += 1
        languag.spanish(oeh) = "opinión / informe de fallo / feature request"
        oeh += 1
        languag.spanish(oeh) = "cerca"
        oeh += 1
        languag.spanish(oeh) = "Enviar"
        oeh += 1
        languag.spanish(oeh) = "Después de 3 Opiniones envío de comentarios sólo es posible mañana."
        oeh += 1
        languag.spanish(oeh) = "Una aportación mínima de 10 caracteres es Requiere."
        oeh += 1
        languag.spanish(oeh) = "votos no se transmite."
        oeh += 1
        languag.spanish(oeh) = "reducir al mínimo el arranque automático"
        oeh += 1
        languag.spanish(oeh) = "Automatic Save"
        oeh += 1
        languag.spanish(oeh) = "Segundos"
        oeh += 1
        languag.spanish(oeh) = "desplazamiento"



        oeh = 0
        '        languag.russian(oeh) = "Меню"
        '        oeh += 1
        '        languag.russian(oeh) = "Новый файл Ctrl + N"
        '        oeh += 1
        '        languag.russian(oeh) = "Открытое CTRL + O"
        '        oeh += 1
        '        languag.russian(oeh) = "Сохранить CTRL + S"
        '        oeh += 1
        '        languag.russian(oeh) = "Сохранить как"
        '        oeh += 1
        '        languag.russian(oeh) = "Закрыть"
        '        oeh += 1
        '        languag.russian(oeh) = "Настройки"
        '        oeh += 1
        '        languag.russian(oeh) = "Выйти Ctrl + Q"
        '        oeh += 1
        '        languag.russian(oeh) = "Помощь"
        '        oeh += 1
        '        languag.russian(oeh) = "для программиста, я надеюсь на это"
        '        oeh += 1
        '        languag.russian(oeh) = "новый файл"
        '        oeh += 1
        '        languag.russian(oeh) = "открытой"
        '        oeh += 1
        '        languag.russian(oeh) = "Сохранить"
        '        oeh += 1
        '        languag.russian(oeh) = "Закрыть"
        '        oeh += 1
        '        languag.russian(oeh) = "Печать"
        '        oeh += 1
        '        languag.russian(oeh) = "Шрифт"
        '        oeh += 1
        '        languag.russian(oeh) = "Смена"
        '        oeh += 1
        '        languag.russian(oeh) = "новый / удалить"
        '        oeh += 1
        '        languag.russian(oeh) = "toolstrips"
        '        oeh += 1
        '        languag.russian(oeh) = "Шрифт"
        '        oeh += 1
        '        languag.russian(oeh) = "новых элементов"
        '        oeh += 1
        '        languag.russian(oeh) = "Удалить элемент"
        '        oeh += 1
        '        languag.russian(oeh) = "Вырезать Ctrl + X"
        '        oeh += 1
        '        languag.russian(oeh) = "Копировать Ctrl + C"
        '        oeh += 1
        '        languag.russian(oeh) = "Вставить Ctrl + V"
        '        oeh += 1
        '        languag.russian(oeh) = "Настройки"
        '        oeh += 1
        '        languag.russian(oeh) = "Показать в панель поиска"
        '        oeh += 1
        '        languag.russian(oeh) = "язык"
        '        oeh += 1
        '        languag.russian(oeh) = "OK"
        '        oeh += 1
        '        languag.russian(oeh) = "Копировать"
        '        oeh += 1
        '        languag.russian(oeh) = "Вырезать"
        '        oeh += 1
        '        languag.russian(oeh) = "Вставить"
        '        oeh += 1
        '        languag.russian(oeh) = "Удалить"
        '        oeh += 1
        '        languag.russian(oeh) = "Поиск"
        '        oeh += 1
        '        languag.russian(oeh) = "Поиск"
        '        oeh += 1
        '        languag.russian(oeh) = "под новым [Ins]"
        '        oeh += 1
        '        languag.russian(oeh) = "Переименовать"
        '        oeh += 1
        '        languag.russian(oeh) = "Удалить [деле]"
        '        oeh += 1
        '        languag.russian(oeh) = "Сохранить"
        '        oeh += 1
        '        languag.russian(oeh) = "столе записки"
        '        oeh += 1
        '        languag.russian(oeh) = "Вы хотите удалить этот узел?"
        '        oeh += 1
        '        languag.russian(oeh) = "Да"
        '        oeh += 1
        '        languag.russian(oeh) = "Нет"
        '        oeh += 1
        '        languag.russian(oeh) = "отмечает, дерево"
        '        oeh += 1
        '        languag.russian(oeh) = "место, где показано Заметки"
        '        oeh += 1
        '        languag.russian(oeh) = "Показать / Скрыть"
        '        oeh += 1
        '        languag.russian(oeh) = "Поиск"
        '        oeh += 1
        '        languag.russian(oeh) = "Назад"
        '        oeh += 1
        '        languag.russian(oeh) = "Поиск Все узлы"
        '        oeh += 1
        '        languag.russian(oeh) = "Результат:"
        '        oeh += 1
        '        languag.russian(oeh) = "Вы хотите сохранить раньше? "
        '        oeh += 1
        '        languag.russian(oeh) = "начинать"
        '        oeh += 1
        '        languag.russian(oeh) = "начинать"
        '        oeh += 1
        '        languag.russian(oeh) = "Данные будут потеряны."
        '        oeh += 1
        '        languag.russian(oeh) = "Вы уверены, что, чтобы начать заново?"
        '        oeh += 1
        '        languag.russian(oeh) = "Вы хотите сохранить раньше? "
        '        oeh += 1
        '        languag.russian(oeh) = "OK"
        '        oeh += 1
        '        languag.russian(oeh) = "Отмена"
        '        oeh += 1
        '        languag.russian(oeh) = "Копировать"
        '        oeh += 1
        '        languag.russian(oeh) = "Вырезать"
        '        oeh += 1
        '        languag.russian(oeh) = "Вставить"
        '        oeh += 1
        '        languag.russian(oeh) = "регулярное шрифт"
        '        oeh += 1
        '        languag.russian(oeh) = "жирный шрифт"
        '        oeh += 1
        '        languag.russian(oeh) = "наклонным шрифтом"
        '        oeh += 1
        '        languag.russian(oeh) = "Подчеркнутый"
        '        oeh += 1
        '        languag.russian(oeh) = "Зачеркнутый"
        '        oeh += 1
        '        languag.russian(oeh) = "большой шрифт"
        '        oeh += 1
        '        languag.russian(oeh) = "мелким шрифтом"
        '        oeh += 1
        '        languag.russian(oeh) = "вместе в один узел"
        '        oeh += 1
        '        languag.russian(oeh) = "Инфо + + Помощь Обратная связь"
        '        oeh += 1
        '        languag.russian(oeh) = "все"
        '        oeh += 1
        '        languag.russian(oeh) = "внутри отмечены узел"
        '        oeh += 1
        '        languag.russian(oeh) = "загружен Файл."
        '        oeh += 1
        '        languag.russian(oeh) = "Ошибка при загрузке XML-код:"
        '        oeh += 1
        '        languag.russian(oeh) = "Установить пароль"
        '        oeh += 1
        '        languag.russian(oeh) = "старый пароль"
        '        oeh += 1
        '        languag.russian(oeh) = "Новый пароль"
        '        oeh += 1
        '        languag.russian(oeh) = "еще раз"
        '        oeh += 1
        '        languag.russian(oeh) = "Допускается Не более 24 символов."
        '        oeh += 1
        '        languag.russian(oeh) = "старый пароль неправильный."
        '        oeh += 1
        '        languag.russian(oeh) = "пароль"
        '        oeh += 1
        '        languag.russian(oeh) = "неправильный пароль или неправильно файл"
        '        oeh += 1
        '        languag.russian(oeh) = "последние 3 entrys не являются равными."
        '        oeh += 1
        '        languag.russian(oeh) = "Пусто текстовое средствами без пароля."
        '        oeh += 1
        '        languag.russian(oeh) = "вставить картинку"
        '        oeh += 1
        '        languag.russian(oeh) = "Дата"
        '        oeh += 1
        '        languag.russian(oeh) = "Цвет фона"
        '        oeh += 1
        '        languag.russian(oeh) = "Свернуть"
        '        oeh += 1
        '        languag.russian(oeh) = "Закрыть"
        '        oeh += 1
        '        languag.russian(oeh) = "Показать Desknote границ"
        '        oeh += 1
        '        languag.russian(oeh) = "Цвет фона"
        '        oeh += 1
        '        languag.russian(oeh) = "Цвет шрифта"
        '        oeh += 1
        '        languag.russian(oeh) = "резервных копий"
        '        oeh += 1
        '        languag.russian(oeh) = "автозапуска"
        '        oeh += 1
        '        languag.russian(oeh) = "Цвет"
        '        oeh += 1
        '        languag.russian(oeh) = "пароль"
        '        oeh += 1
        '        languag.russian(oeh) = "путь + Файл "
        '        oeh += 1
        '        languag.russian(oeh) = "Файл должен заканчиваться на. ALX!"
        '        oeh += 1
        '        languag.russian(oeh) = "экспорт"
        '        oeh += 1
        '        languag.russian(oeh) = "в RTF"
        '        oeh += 1
        '        languag.russian(oeh) = "В ANSI TXT"
        '        oeh += 1
        '        languag.russian(oeh) = "в Unicode TXT"
        '        oeh += 1
        '        languag.russian(oeh) = "Следующий [Enter]"
        '        oeh += 1
        '        languag.russian(oeh) = "в соответствии с [вставить]"
        '        oeh += 1
        '        languag.russian(oeh) = "новый следующий [Enter]"
        '        oeh += 1
        '        languag.russian(oeh) = "Всего слов"
        '        oeh += 1
        '        languag.russian(oeh) = "случае чувствительной"
        '        oeh += 1
        '        languag.russian(oeh) = ChrW(8226) + " A desknote can be created by using the menu of the node and can be reached by the trayicon menu." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
        'ChrW(8226) + " Nodes can be summed up as rtf file, witch can be read with Wordpad, Word or OpenOffice." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
        'ChrW(8226) + " Create a Link with with a destination: ""C:\Ort1\notizen.exe"" -min ""C:\Dokumente und Einstellungen\Benutzer\Eigene Dateien\Notizen\datei.alx"" , first notizen.exe and the alx file, the program will be opend by opening the File. Both Locations should be better into double quotes. If you put the link into the autostart folder you have your notes by starting the Computer." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
        'ChrW(8226) + " The argument /min after notizen.exe, maybe in a line of a link, makes the programm running minimized at startup. (notizen.exe /min destination file)"" " + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
        '     ChrW(8226) + "If you run Notizen .Net with Administrator permissions once, the explorer will know Notizen .NET alx Files."
        '        oeh += 1
        '        languag.russian(oeh) = "Мнение / сообщение об ошибке / Запрос функции"
        '        oeh += 1
        '        languag.russian(oeh) = "Закрыть"
        '        oeh += 1
        '        languag.russian(oeh) = "Отправить"
        '        oeh += 1
        '        languag.russian(oeh) = "После 3 Отзывы отправка отзыва возможна только завтра."
        '        oeh += 1
        '        languag.russian(oeh) = "является минимальный ввод 10 символов."
        '        oeh += 1
        '        languag.russian(oeh) = "обратной связи не было передано."
        '        oeh += 1
        '        languag.russian(oeh) = "свести к минимуму автоматического запуска"
        '        oeh += 1
        '        languag.russian(oeh) = "автоматически сохранит каждый"
        '        oeh += 1
        '        languag.russian(oeh) = "секунда"
        '        oeh += 1
        '        languag.russian(oeh) = "прокрутки"
        languag.russian(oeh) = "Меню"
        oeh += 1
        languag.russian(oeh) = "Новый файл Ctrl + N"
        oeh += 1
        languag.russian(oeh) = "Открыть CTRL + O"
        oeh += 1
        languag.russian(oeh) = "Сохранить CTRL + S"
        oeh += 1
        languag.russian(oeh) = "Сохранить как"
        oeh += 1
        languag.russian(oeh) = "Закрыть"
        oeh += 1
        languag.russian(oeh) = "Настройки"
        oeh += 1
        languag.russian(oeh) = "Выйти Ctrl + Q"
        oeh += 1
        languag.russian(oeh) = "Помощь"
        oeh += 1
        languag.russian(oeh) = "для программиста, я надеюсь на это"
        oeh += 1
        languag.russian(oeh) = "новый файл"
        oeh += 1
        languag.russian(oeh) = "открыть"
        oeh += 1
        languag.russian(oeh) = "Сохранить"
        oeh += 1
        languag.russian(oeh) = "Закрыть"
        oeh += 1
        languag.russian(oeh) = "Печать"
        oeh += 1
        languag.russian(oeh) = "Шрифт"
        oeh += 1
        languag.russian(oeh) = "Смена"
        oeh += 1
        languag.russian(oeh) = "новый / удалить"
        oeh += 1
        languag.russian(oeh) = "toolstrips"
        oeh += 1
        languag.russian(oeh) = "Шрифт"
        oeh += 1
        languag.russian(oeh) = "новых элементов"
        oeh += 1
        languag.russian(oeh) = "Удалить элемент"
        oeh += 1
        languag.russian(oeh) = "Вырезать Ctrl + X"
        oeh += 1
        languag.russian(oeh) = "Копировать Ctrl + C"
        oeh += 1
        languag.russian(oeh) = "Вставить Ctrl + V"
        oeh += 1
        languag.russian(oeh) = "Настройки"
        oeh += 1
        languag.russian(oeh) = "сделали видимыми на панели задач"
        oeh += 1
        languag.russian(oeh) = "язык"
        oeh += 1
        languag.russian(oeh) = "OK"
        oeh += 1
        languag.russian(oeh) = "Копировать"
        oeh += 1
        languag.russian(oeh) = "Вырезать"
        oeh += 1
        languag.russian(oeh) = "Вставить"
        oeh += 1
        languag.russian(oeh) = "Удалить"
        oeh += 1
        languag.russian(oeh) = "Поиск"
        oeh += 1
        languag.russian(oeh) = "Поиск"
        oeh += 1
        languag.russian(oeh) = "под новым [Ins]"
        oeh += 1
        languag.russian(oeh) = "Переименовать"
        oeh += 1
        languag.russian(oeh) = "Удалить [деле]"
        oeh += 1
        languag.russian(oeh) = "Сохранить"
        oeh += 1
        languag.russian(oeh) = "столе записки"
        oeh += 1
        languag.russian(oeh) = "Вы хотите удалить этот узел?"
        oeh += 1
        languag.russian(oeh) = "Да"
        oeh += 1
        languag.russian(oeh) = "Нет"
        oeh += 1
        languag.russian(oeh) = "отмечает, дерево"
        oeh += 1
        languag.russian(oeh) = "место, где показаны Заметки"
        oeh += 1
        languag.russian(oeh) = "Показать / Скрыть"
        oeh += 1
        languag.russian(oeh) = "Поиск"
        oeh += 1
        languag.russian(oeh) = "Назад"
        oeh += 1
        languag.russian(oeh) = "Поиск Всех узлов"
        oeh += 1
        languag.russian(oeh) = "Результат:"
        oeh += 1
        languag.russian(oeh) = "Вы хотите сначала сохранить? "
        oeh += 1
        languag.russian(oeh) = "начинать"
        oeh += 1
        languag.russian(oeh) = "начинать"
        oeh += 1
        languag.russian(oeh) = "Данные будут потеряны."
        oeh += 1
        languag.russian(oeh) = "Вы уверены, что хотите начать заново?"
        oeh += 1
        languag.russian(oeh) = "Вы хотите сначала сохранить? "
        oeh += 1
        languag.russian(oeh) = "OK"
        oeh += 1
        languag.russian(oeh) = "Отмена"
        oeh += 1
        languag.russian(oeh) = "Копировать"
        oeh += 1
        languag.russian(oeh) = "Вырезать"
        oeh += 1
        languag.russian(oeh) = "Вставить"
        oeh += 1
        languag.russian(oeh) = "Обычный шрифт"
        oeh += 1
        languag.russian(oeh) = "Жирный шрифт"
        oeh += 1
        languag.russian(oeh) = "Курсив"
        oeh += 1
        languag.russian(oeh) = "Подчеркнутый"
        oeh += 1
        languag.russian(oeh) = "Зачеркнутый"
        oeh += 1
        languag.russian(oeh) = "Большой шрифт"
        oeh += 1
        languag.russian(oeh) = "Мелкий шрифт"
        oeh += 1
        languag.russian(oeh) = "вместе в один узел"
        oeh += 1
        languag.russian(oeh) = "Инфо + + Помощь Обратная связь"
        oeh += 1
        languag.russian(oeh) = "все"
        oeh += 1
        languag.russian(oeh) = "ниже отмечены узлы"
        oeh += 1
        languag.russian(oeh) = "Не был загружен файл"
        oeh += 1
        languag.russian(oeh) = "Ошибка при загрузке XML-код:"
        oeh += 1
        languag.russian(oeh) = "Установить пароль"
        oeh += 1
        languag.russian(oeh) = "Старый пароль"
        oeh += 1
        languag.russian(oeh) = "Новый пароль"
        oeh += 1
        languag.russian(oeh) = "еще раз"
        oeh += 1
        languag.russian(oeh) = "Допускается Не более 24 символов."
        oeh += 1
        languag.russian(oeh) = "старый пароль неправильный."
        oeh += 1
        languag.russian(oeh) = "пароль"
        oeh += 1
        languag.russian(oeh) = "неправильный пароль или неправильный файл"
        oeh += 1
        languag.russian(oeh) = "последние 3 символа не одинаковы."
        oeh += 1
        languag.russian(oeh) = "Пусто текстовое средствами без пароля."
        oeh += 1
        languag.russian(oeh) = "вставить картинку"
        oeh += 1
        languag.russian(oeh) = "Дата"
        oeh += 1
        languag.russian(oeh) = "Цвет фона"
        oeh += 1
        languag.russian(oeh) = "Свернуть"
        oeh += 1
        languag.russian(oeh) = "Закрыть"
        oeh += 1
        languag.russian(oeh) = "Показать границы Desknote"
        oeh += 1
        languag.russian(oeh) = "Цвет фона"
        oeh += 1
        languag.russian(oeh) = "Цвет шрифта"
        oeh += 1
        languag.russian(oeh) = "резервные копии"
        oeh += 1
        languag.russian(oeh) = "автозапуск"
        oeh += 1
        languag.russian(oeh) = "Цвет"
        oeh += 1
        languag.russian(oeh) = "пароль"
        oeh += 1
        languag.russian(oeh) = "путь + Файл "
        oeh += 1
        languag.russian(oeh) = "Файл должен заканчиваться на. ALX!"
        oeh += 1
        languag.russian(oeh) = "экспорт"
        oeh += 1
        languag.russian(oeh) = "в RTF"
        oeh += 1
        languag.russian(oeh) = "В ANSI TXT"
        oeh += 1
        languag.russian(oeh) = "в Unicode TXT"
        oeh += 1
        languag.russian(oeh) = "Следующий [Enter]"
        oeh += 1
        languag.russian(oeh) = "под [вставить]"
        oeh += 1
        languag.russian(oeh) = "новый следующий [Enter]"
        oeh += 1
        languag.russian(oeh) = "Всего слов"
        oeh += 1
        languag.russian(oeh) = "случае чувствительной"
        oeh += 1
        languag.russian(oeh) = ChrW(8226) + " A desknote can be created by using the menu of the node and can be reached by the trayicon menu." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " Nodes can be summed up as rtf file, witch can be read with Wordpad, Word or OpenOffice." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " Create a Link with with a destination: ""C:\Ort1\notizen.exe"" -min ""C:\Dokumente und Einstellungen\Benutzer\Eigene Dateien\Notizen\datei.alx"" , first notizen.exe and the alx file, the program will be opend by opening the File. Both Locations should be better into double quotes. If you put the link into the autostart folder you have your notes by starting the Computer." + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
ChrW(8226) + " The argument /min after notizen.exe, maybe in a line of a link, makes the programm running minimized at startup. (notizen.exe /min destination file)"" " + Chr(13) + Chr(10) + Chr(13) + Chr(10) + _
     ChrW(8226) + "If you run Notizen .Net with Administrator permissions once, the explorer will know Notizen .NET alx Files."
        oeh += 1
        languag.russian(oeh) = "Мнение / сообщение об ошибке / Запрос функции"
        oeh += 1
        languag.russian(oeh) = "Закрыть"
        oeh += 1
        languag.russian(oeh) = "Отправить"
        oeh += 1
        languag.russian(oeh) = "После 3 Отзывы отправка отзыва возможна только завтра."
        oeh += 1
        languag.russian(oeh) = "является минимальный ввод 10 символов."
        oeh += 1
        languag.russian(oeh) = "обратной связи не было передано."
        oeh += 1
        languag.russian(oeh) = "свести к минимуму автоматического запуска"
        oeh += 1
        languag.russian(oeh) = "автоматически сохранит каждый"
        oeh += 1
        languag.russian(oeh) = "секунда"
        oeh += 1
        languag.russian(oeh) = "прокрутки"
        Return languag
    End Function
End Class